apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "task-manager.fullname" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_JSON: {{ .Values.env.logJSON | quote }}
