name: Infra CD

on:
  workflow_run:
    workflows: ["App CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Infrastructure
    # Use self-hosted runner as requested
    runs-on: arc-runner-set
    # Only run if the previous App CI workflow was successful AND it's main or develop
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'develop') }}

    # Dynamically select 'prod' or 'dev' environment in GitHub Actions (forces approval for prod if configured in repo settings)
    environment:
      name: ${{ github.event.workflow_run.head_branch == 'main' && 'prod' || 'dev' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
      TF_VAR_image_tag: ${{ github.event.workflow_run.head_sha }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_github_pat: ${{ secrets.PAT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set Terraform Working Directory
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            echo "TF_DIR=infrastructure/environments/prod" >> $GITHUB_ENV
          else
            echo "TF_DIR=infrastructure/environments/dev" >> $GITHUB_ENV
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions-sa@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve tfplan

      - name: Get Ingress URL
        id: ingress
        working-directory: ${{ env.TF_DIR }}
        run: echo "URL=$(terraform output -raw ingress_url)" >> $GITHUB_ENV

      - name: Setup Python (for Locust)
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Locust
        run: pip install locust

      - name: Run Load Test
        working-directory: locust
        run: >
          locust -f locustfile.py
          --headless
          -u 10
          -r 2
          --run-time 1m
          --host ${{ env.URL }}
